Repository testdriverai/testdriverai, pull requests merged in 2025-06, with the labels that each got.

#247 Theme the CLI output and code highlights
  agent.js
  index.js
  lib/commander.js
  lib/commands.js
  lib/config.js
  lib/events.js
  lib/focus-application.js
  lib/generator.js
  lib/init.js
  lib/logger.js
  lib/network.js
  lib/outputs.js
  lib/parser.js
  lib/redraw.js
  lib/resources/prerun.yaml
  lib/sandbox.js
  lib/sdk.js
  lib/session.js
  lib/system.js
  lib/theme.js
  lib/upload-secrets.js
Labels: enhancement

#260 TD-1912 – Recommend npx over npm i -g
  .github/workflows/test-install.yml
  README.md
  docs/apps/static-websites.mdx
  docs/cli/overview.mdx
  docs/features/generation.mdx
  docs/getting-started/editing.mdx
  docs/getting-started/generating.mdx
  docs/getting-started/running.mdx
  docs/getting-started/setup.mdx
  docs/getting-started/vscode.mdx
  docs/guide/lifecycle-prerun.mdx
  docs/importing/gherkin.mdx
  docs/importing/jira.mdx
  docs/importing/testrail.mdx
  docs/interactive/dry.mdx
  docs/interactive/explore.mdx
  docs/overview/quickstart.mdx
  docs/quickstart.mdx
  docs/scenarios/log-in.mdx
  docs/snippets/test-prereqs.mdx
  docs/tutorials/basic-test.mdx
  package.json
Labels: enhancement

#266 Force `dieOnFatal` if `--heal` not enabled
  agent.js
Labels: urgent

#290 docs: Add tip on how to scroll to the top/bottom of the page reliably
  docs/commands/issues.mdx
  docs/commands/scroll.mdx
Labels: documentation
